// @generated by protobuf-ts 2.9.4 with parameter long_type_number,generate_dependencies,ts_nocheck,output_typescript
// @generated from protobuf file "v1/integration_provider_trufund.proto" (syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { LoadModel_InvoiceStatus } from "./models/model_load";
import { LoadModel_Status } from "./models/model_load";
/**
 * TruFund - Get Invoices Preview
 *
 * @generated from protobuf message IP_TruFund_Invoices_PreviewRequest
 */
export interface IP_TruFund_Invoices_PreviewRequest {
}
/**
 * @generated from protobuf message IP_TruFund_Invoices_PreviewReply
 */
export interface IP_TruFund_Invoices_PreviewReply {
    /**
     * @generated from protobuf field: string totalAmount = 1;
     */
    totalAmount: string;
    /**
     * @generated from protobuf field: string totalFactoringAmount = 2;
     */
    totalFactoringAmount: string;
    /**
     * @generated from protobuf field: string totalCompanyNet = 3;
     */
    totalCompanyNet: string;
    /**
     * @generated from protobuf field: repeated IP_TruFund_Invoices_PreviewReply.Invoice invoices = 4;
     */
    invoices: IP_TruFund_Invoices_PreviewReply_Invoice[];
}
/**
 * @generated from protobuf message IP_TruFund_Invoices_PreviewReply.Invoice
 */
export interface IP_TruFund_Invoices_PreviewReply_Invoice {
    /**
     * @generated from protobuf field: string load_friendly_id = 1;
     */
    loadFriendlyId: string;
    /**
     * @generated from protobuf field: string load_reference_id = 2;
     */
    loadReferenceId: string;
    /**
     * @generated from protobuf field: string broker_id = 3;
     */
    brokerId: string;
    /**
     * @generated from protobuf field: string customer_id = 4;
     */
    customerId: string;
    /**
     * @generated from protobuf field: string load_id = 5;
     */
    loadId: string;
    /**
     * @generated from protobuf field: LoadModel.Status status = 6;
     */
    status: LoadModel_Status;
    /**
     * @generated from protobuf field: LoadModel.InvoiceStatus invoice_status = 7;
     */
    invoiceStatus: LoadModel_InvoiceStatus;
    /**
     * @generated from protobuf field: string amount = 8;
     */
    amount: string;
    /**
     * @generated from protobuf field: string factoring_amount = 9;
     */
    factoringAmount: string;
    /**
     * @generated from protobuf field: bool has_errors = 10;
     */
    hasErrors: boolean;
    /**
     * @generated from protobuf field: repeated string errors = 11;
     */
    errors: string[];
}
/**
 * TruFund - Create Invoices
 *
 * @generated from protobuf message IP_TruFund_Invoices_Create_Request
 */
export interface IP_TruFund_Invoices_Create_Request {
    /**
     * @generated from protobuf field: repeated string load_ids = 1;
     */
    loadIds: string[];
}
/**
 * @generated from protobuf message IP_TruFund_Invoices_Create_Reply
 */
export interface IP_TruFund_Invoices_Create_Reply {
    /**
     * @generated from protobuf field: string load_id = 1;
     */
    loadId: string;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: IP_TruFund_Invoices_CreateReply_Enum_Code.Code code = 3;
     */
    code: IP_TruFund_Invoices_CreateReply_Enum_Code_Code;
}
/**
 * @generated from protobuf message IP_TruFund_Invoices_CreateReply_Enum_Code
 */
export interface IP_TruFund_Invoices_CreateReply_Enum_Code {
}
/**
 * @generated from protobuf enum IP_TruFund_Invoices_CreateReply_Enum_Code.Code
 */
export enum IP_TruFund_Invoices_CreateReply_Enum_Code_Code {
    /**
     * @generated from protobuf enum value: CODE_SUCCESS = 0;
     */
    SUCCESS = 0,
    /**
     * @generated from protobuf enum value: CODE_WARN = 1;
     */
    WARN = 1,
    /**
     * @generated from protobuf enum value: CODE_FAILED = 2;
     */
    FAILED = 2,
    /**
     * @generated from protobuf enum value: CODE_INTERNAL_ERROR = 3;
     */
    INTERNAL_ERROR = 3,
    /**
     * @generated from protobuf enum value: CODE_UNKNOWN = 4;
     */
    UNKNOWN = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_PreviewRequest$Type extends MessageType<IP_TruFund_Invoices_PreviewRequest> {
    constructor() {
        super("IP_TruFund_Invoices_PreviewRequest", []);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_PreviewRequest>): IP_TruFund_Invoices_PreviewRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_PreviewRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_PreviewRequest): IP_TruFund_Invoices_PreviewRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_PreviewRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_PreviewRequest
 */
export const IP_TruFund_Invoices_PreviewRequest = new IP_TruFund_Invoices_PreviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_PreviewReply$Type extends MessageType<IP_TruFund_Invoices_PreviewReply> {
    constructor() {
        super("IP_TruFund_Invoices_PreviewReply", [
            { no: 1, name: "totalAmount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "totalFactoringAmount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "totalCompanyNet", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "invoices", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => IP_TruFund_Invoices_PreviewReply_Invoice }
        ]);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_PreviewReply>): IP_TruFund_Invoices_PreviewReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalAmount = "";
        message.totalFactoringAmount = "";
        message.totalCompanyNet = "";
        message.invoices = [];
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_PreviewReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_PreviewReply): IP_TruFund_Invoices_PreviewReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string totalAmount */ 1:
                    message.totalAmount = reader.string();
                    break;
                case /* string totalFactoringAmount */ 2:
                    message.totalFactoringAmount = reader.string();
                    break;
                case /* string totalCompanyNet */ 3:
                    message.totalCompanyNet = reader.string();
                    break;
                case /* repeated IP_TruFund_Invoices_PreviewReply.Invoice invoices */ 4:
                    message.invoices.push(IP_TruFund_Invoices_PreviewReply_Invoice.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_PreviewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string totalAmount = 1; */
        if (message.totalAmount !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.totalAmount);
        /* string totalFactoringAmount = 2; */
        if (message.totalFactoringAmount !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.totalFactoringAmount);
        /* string totalCompanyNet = 3; */
        if (message.totalCompanyNet !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.totalCompanyNet);
        /* repeated IP_TruFund_Invoices_PreviewReply.Invoice invoices = 4; */
        for (let i = 0; i < message.invoices.length; i++)
            IP_TruFund_Invoices_PreviewReply_Invoice.internalBinaryWrite(message.invoices[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_PreviewReply
 */
export const IP_TruFund_Invoices_PreviewReply = new IP_TruFund_Invoices_PreviewReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_PreviewReply_Invoice$Type extends MessageType<IP_TruFund_Invoices_PreviewReply_Invoice> {
    constructor() {
        super("IP_TruFund_Invoices_PreviewReply.Invoice", [
            { no: 1, name: "load_friendly_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "load_reference_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "broker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "customer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "load_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status", kind: "enum", T: () => ["LoadModel.Status", LoadModel_Status] },
            { no: 7, name: "invoice_status", kind: "enum", T: () => ["LoadModel.InvoiceStatus", LoadModel_InvoiceStatus] },
            { no: 8, name: "amount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "factoring_amount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "has_errors", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "errors", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_PreviewReply_Invoice>): IP_TruFund_Invoices_PreviewReply_Invoice {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.loadFriendlyId = "";
        message.loadReferenceId = "";
        message.brokerId = "";
        message.customerId = "";
        message.loadId = "";
        message.status = 0;
        message.invoiceStatus = 0;
        message.amount = "";
        message.factoringAmount = "";
        message.hasErrors = false;
        message.errors = [];
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_PreviewReply_Invoice>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_PreviewReply_Invoice): IP_TruFund_Invoices_PreviewReply_Invoice {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string load_friendly_id */ 1:
                    message.loadFriendlyId = reader.string();
                    break;
                case /* string load_reference_id */ 2:
                    message.loadReferenceId = reader.string();
                    break;
                case /* string broker_id */ 3:
                    message.brokerId = reader.string();
                    break;
                case /* string customer_id */ 4:
                    message.customerId = reader.string();
                    break;
                case /* string load_id */ 5:
                    message.loadId = reader.string();
                    break;
                case /* LoadModel.Status status */ 6:
                    message.status = reader.int32();
                    break;
                case /* LoadModel.InvoiceStatus invoice_status */ 7:
                    message.invoiceStatus = reader.int32();
                    break;
                case /* string amount */ 8:
                    message.amount = reader.string();
                    break;
                case /* string factoring_amount */ 9:
                    message.factoringAmount = reader.string();
                    break;
                case /* bool has_errors */ 10:
                    message.hasErrors = reader.bool();
                    break;
                case /* repeated string errors */ 11:
                    message.errors.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_PreviewReply_Invoice, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string load_friendly_id = 1; */
        if (message.loadFriendlyId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.loadFriendlyId);
        /* string load_reference_id = 2; */
        if (message.loadReferenceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.loadReferenceId);
        /* string broker_id = 3; */
        if (message.brokerId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.brokerId);
        /* string customer_id = 4; */
        if (message.customerId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.customerId);
        /* string load_id = 5; */
        if (message.loadId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.loadId);
        /* LoadModel.Status status = 6; */
        if (message.status !== 0)
            writer.tag(6, WireType.Varint).int32(message.status);
        /* LoadModel.InvoiceStatus invoice_status = 7; */
        if (message.invoiceStatus !== 0)
            writer.tag(7, WireType.Varint).int32(message.invoiceStatus);
        /* string amount = 8; */
        if (message.amount !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.amount);
        /* string factoring_amount = 9; */
        if (message.factoringAmount !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.factoringAmount);
        /* bool has_errors = 10; */
        if (message.hasErrors !== false)
            writer.tag(10, WireType.Varint).bool(message.hasErrors);
        /* repeated string errors = 11; */
        for (let i = 0; i < message.errors.length; i++)
            writer.tag(11, WireType.LengthDelimited).string(message.errors[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_PreviewReply.Invoice
 */
export const IP_TruFund_Invoices_PreviewReply_Invoice = new IP_TruFund_Invoices_PreviewReply_Invoice$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_Create_Request$Type extends MessageType<IP_TruFund_Invoices_Create_Request> {
    constructor() {
        super("IP_TruFund_Invoices_Create_Request", [
            { no: 1, name: "load_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_Create_Request>): IP_TruFund_Invoices_Create_Request {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.loadIds = [];
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_Create_Request>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_Create_Request): IP_TruFund_Invoices_Create_Request {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string load_ids */ 1:
                    message.loadIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_Create_Request, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string load_ids = 1; */
        for (let i = 0; i < message.loadIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.loadIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_Create_Request
 */
export const IP_TruFund_Invoices_Create_Request = new IP_TruFund_Invoices_Create_Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_Create_Reply$Type extends MessageType<IP_TruFund_Invoices_Create_Reply> {
    constructor() {
        super("IP_TruFund_Invoices_Create_Reply", [
            { no: 1, name: "load_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "code", kind: "enum", T: () => ["IP_TruFund_Invoices_CreateReply_Enum_Code.Code", IP_TruFund_Invoices_CreateReply_Enum_Code_Code, "CODE_"] }
        ]);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_Create_Reply>): IP_TruFund_Invoices_Create_Reply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.loadId = "";
        message.message = "";
        message.code = 0;
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_Create_Reply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_Create_Reply): IP_TruFund_Invoices_Create_Reply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string load_id */ 1:
                    message.loadId = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* IP_TruFund_Invoices_CreateReply_Enum_Code.Code code */ 3:
                    message.code = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_Create_Reply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string load_id = 1; */
        if (message.loadId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.loadId);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* IP_TruFund_Invoices_CreateReply_Enum_Code.Code code = 3; */
        if (message.code !== 0)
            writer.tag(3, WireType.Varint).int32(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_Create_Reply
 */
export const IP_TruFund_Invoices_Create_Reply = new IP_TruFund_Invoices_Create_Reply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IP_TruFund_Invoices_CreateReply_Enum_Code$Type extends MessageType<IP_TruFund_Invoices_CreateReply_Enum_Code> {
    constructor() {
        super("IP_TruFund_Invoices_CreateReply_Enum_Code", []);
    }
    create(value?: PartialMessage<IP_TruFund_Invoices_CreateReply_Enum_Code>): IP_TruFund_Invoices_CreateReply_Enum_Code {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<IP_TruFund_Invoices_CreateReply_Enum_Code>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IP_TruFund_Invoices_CreateReply_Enum_Code): IP_TruFund_Invoices_CreateReply_Enum_Code {
        return target ?? this.create();
    }
    internalBinaryWrite(message: IP_TruFund_Invoices_CreateReply_Enum_Code, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IP_TruFund_Invoices_CreateReply_Enum_Code
 */
export const IP_TruFund_Invoices_CreateReply_Enum_Code = new IP_TruFund_Invoices_CreateReply_Enum_Code$Type();
/**
 * @generated ServiceType for protobuf service IntegrationProviderTruFund
 */
export const IntegrationProviderTruFund = new ServiceType("IntegrationProviderTruFund", [
    { name: "IP_TruFund_Invoices_Preview", options: {}, I: IP_TruFund_Invoices_PreviewRequest, O: IP_TruFund_Invoices_PreviewReply },
    { name: "IP_TruFund_Invoices_Create", serverStreaming: true, options: {}, I: IP_TruFund_Invoices_Create_Request, O: IP_TruFund_Invoices_Create_Reply }
]);
