import { PERMISSIONS } from '@/models/permissions/permissions';

export const NAVIGATION_MAP = {
    HOME    : [PERMISSIONS.HOME_PAGE],
    DISPATCH: [
        PERMISSIONS.LOADS_PAGE,
        PERMISSIONS.SCHEDULING_PAGE,
        PERMISSIONS.STATS_PAGE,
        PERMISSIONS.BROKERS_PAGE,
        PERMISSIONS.CUSTOMERS_PAGE
    ],
    FLEET: [
        PERMISSIONS.PLATES_PAGE,
        PERMISSIONS.TRUCKS_PAGE,
        PERMISSIONS.TRAILERS_PAGE,
        PERMISSIONS.DRIVERS_PAGE,
        PERMISSIONS.VENDORS_PAGE
    ],
    FINANCE: [
        PERMISSIONS.INVOICES_PAGE,
        PERMISSIONS.SETTLEMENTS_PAGE,
        PERMISSIONS.RECURRING_TRANSACTIONS_PAGE,
        PERMISSIONS.TOLLS_PAGE,
        PERMISSIONS.FUEL_PAGE
    ],
    REPORTS : [PERMISSIONS.IFTA_PAGE],
    SETTINGS: [PERMISSIONS.SETTINGS_PAGE]
};

export type GroupName = 'DISPATCH' | 'FLEET' | 'FINANCE' | 'REPORTS' | 'SETTINGS' | 'HOME';
