// @generated by protobuf-ts 2.9.4 with parameter long_type_number,generate_dependencies,ts_nocheck,output_typescript
// @generated from protobuf file "v1/models/model_tag.proto" (syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message TagModel
 */
export interface TagModel {
}
/**
 * @generated from protobuf enum TagModel.EntityType
 */
export enum TagModel_EntityType {
    /**
     * @generated from protobuf enum value: ENTITY_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ENTITY_TYPE_DRIVER = 1;
     */
    DRIVER = 1,
    /**
     * @generated from protobuf enum value: ENTITY_TYPE_TRAILER = 2;
     */
    TRAILER = 2,
    /**
     * @generated from protobuf enum value: ENTITY_TYPE_TRUCK = 3;
     */
    TRUCK = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class TagModel$Type extends MessageType<TagModel> {
    constructor() {
        super("TagModel", []);
    }
    create(value?: PartialMessage<TagModel>): TagModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<TagModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TagModel): TagModel {
        return target ?? this.create();
    }
    internalBinaryWrite(message: TagModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TagModel
 */
export const TagModel = new TagModel$Type();
