// @generated by protobuf-ts 2.9.4 with parameter long_type_number,generate_dependencies,ts_nocheck,output_typescript
// @generated from protobuf file "v1/models/model_user.proto" (syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message UserModel
 */
export interface UserModel {
}
/**
 * @generated from protobuf message UserModel.Invite
 */
export interface UserModel_Invite {
}
/**
 * @generated from protobuf enum UserModel.Invite.Status
 */
export enum UserModel_Invite_Status {
    /**
     * @generated from protobuf enum value: STATUS_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: STATUS_ACTIVE = 1;
     */
    ACTIVE = 1,
    /**
     * @generated from protobuf enum value: STATUS_ACCEPTED = 2;
     */
    ACCEPTED = 2,
    /**
     * @generated from protobuf enum value: STATUS_DELETED = 3;
     */
    DELETED = 3
}
/**
 * @generated from protobuf enum UserModel.Status
 */
export enum UserModel_Status {
    /**
     * @generated from protobuf enum value: STATUS_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: STATUS_INVITED = 1;
     */
    INVITED = 1,
    /**
     * @generated from protobuf enum value: STATUS_ACTIVE = 2;
     */
    ACTIVE = 2,
    /**
     * @generated from protobuf enum value: STATUS_DISABLED = 3;
     */
    DISABLED = 3,
    /**
     * @generated from protobuf enum value: STATUS_DELETED = 4;
     */
    DELETED = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class UserModel$Type extends MessageType<UserModel> {
    constructor() {
        super("UserModel", []);
    }
    create(value?: PartialMessage<UserModel>): UserModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UserModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserModel): UserModel {
        return target ?? this.create();
    }
    internalBinaryWrite(message: UserModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserModel
 */
export const UserModel = new UserModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserModel_Invite$Type extends MessageType<UserModel_Invite> {
    constructor() {
        super("UserModel.Invite", []);
    }
    create(value?: PartialMessage<UserModel_Invite>): UserModel_Invite {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UserModel_Invite>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserModel_Invite): UserModel_Invite {
        return target ?? this.create();
    }
    internalBinaryWrite(message: UserModel_Invite, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserModel.Invite
 */
export const UserModel_Invite = new UserModel_Invite$Type();
