import { Countries } from '@/models/country/country';

export const USA_STATES = [
    { name: 'Alabama', value: 'AL' },
    { name: 'Alaska', value: 'AK' },
    { name: 'Arizona', value: 'AZ' },
    { name: 'Arkansas', value: 'AR' },
    { name: 'California', value: 'CA' },
    { name: 'Colorado', value: 'CO' },
    { name: 'Connecticut', value: 'CT' },
    { name: 'Delaware', value: 'DE' },
    { name: 'District of Columbia', value: 'DC' },
    { name: 'Florida', value: 'FL' },
    { name: 'Georgia', value: 'GA' },
    { name: 'Hawaii', value: 'HI' },
    { name: 'Idaho', value: 'ID' },
    { name: 'Illinois', value: 'IL' },
    { name: 'Indiana', value: 'IN' },
    { name: 'Iowa', value: 'IA' },
    { name: 'Kansas', value: 'KS' },
    { name: 'Kentucky', value: 'KY' },
    { name: 'Lousiana', value: 'LA' },
    { name: 'Maine', value: 'ME' },
    { name: 'Maryland', value: 'MD' },
    { name: 'Massachusetts', value: 'MA' },
    { name: 'Michigan', value: 'MI' },
    { name: 'Minnesota', value: 'MN' },
    { name: 'Mississippi', value: 'MS' },
    { name: 'Missouri', value: 'MO' },
    { name: 'Montana', value: 'MT' },
    { name: 'Nebraska', value: 'NE' },
    { name: 'Nevada', value: 'NV' },
    { name: 'New Hampshire', value: 'NH' },
    { name: 'New Jersey', value: 'NJ' },
    { name: 'New Mexico', value: 'NM' },
    { name: 'New York', value: 'NY' },
    { name: 'North Carolina', value: 'NC' },
    { name: 'North Dakota', value: 'ND' },
    { name: 'Ohio', value: 'OH' },
    { name: 'Oklahoma', value: 'OK' },
    { name: 'Oregon', value: 'OR' },
    { name: 'Pennsylvania', value: 'PA' },
    { name: 'Rhode Island', value: 'RI' },
    { name: 'South Carolina', value: 'SC' },
    { name: 'South Dakota', value: 'SD' },
    { name: 'Tennessee', value: 'TN' },
    { name: 'Texas', value: 'TX' },
    { name: 'Utah', value: 'UT' },
    { name: 'Vermont', value: 'VT' },
    { name: 'Virginia', value: 'VA' },
    { name: 'Washington', value: 'WA' },
    { name: 'West Virginia', value: 'WV' },
    { name: 'Wisconsin', value: 'WI' },
    { name: 'Wyoming', value: 'WY' }
] as const;

export const PROVINCES_AND_TERRITORIES_CANADA = [
    { name: 'Alberta', value: 'AB' },
    { name: 'British Columbia', value: 'BC' },
    { name: 'Manitoba', value: 'MB' },
    { name: 'New Brunswick', value: 'NB' },
    { name: 'Newfoundland and Labrador', value: 'NL' },
    { name: 'Nova Scotia', value: 'NS' },
    { name: 'Ontario', value: 'ON' },
    { name: 'Prince Edward Island', value: 'PE' },
    { name: 'Quebec', value: 'QC' },
    { name: 'Saskatchewan', value: 'SK' },
    { name: 'Northwest Territories', value: 'NT' }, // Territory
    { name: 'Nunavut', value: 'NU' }, // Territory
    { name: 'Yukon', value: 'YT' } // Territory
] as const;

export const MEXICAN_STATES = [
    { name: 'Aguascalientes', value: 'AGS' },
    { name: 'Baja California', value: 'BC' },
    { name: 'Baja California Sur', value: 'BCS' },
    { name: 'Campeche', value: 'CAMP' },
    { name: 'Chiapas', value: 'CHIS' },
    { name: 'Chihuahua', value: 'CHIH' },
    { name: 'Coahuila', value: 'COAH' },
    { name: 'Colima', value: 'COL' },
    { name: 'Durango', value: 'DGO' },
    { name: 'Guanajuato', value: 'GTO' },
    { name: 'Guerrero', value: 'GRO' },
    { name: 'Hidalgo', value: 'HGO' },
    { name: 'Jalisco', value: 'JAL' },
    { name: 'México (State)', value: 'MEX' },
    { name: 'Michoacán', value: 'MICH' },
    { name: 'Morelos', value: 'MOR' },
    { name: 'Nayarit', value: 'NAY' },
    { name: 'Nuevo León', value: 'NL' },
    { name: 'Oaxaca', value: 'OAX' },
    { name: 'Puebla', value: 'PUE' },
    { name: 'Querétaro', value: 'QRO' },
    { name: 'Quintana Roo', value: 'QROO' },
    { name: 'San Luis Potosí', value: 'SLP' },
    { name: 'Sinaloa', value: 'SIN' },
    { name: 'Sonora', value: 'SON' },
    { name: 'Tabasco', value: 'TAB' },
    { name: 'Tamaulipas', value: 'TAMPS' },
    { name: 'Tlaxcala', value: 'TLAX' },
    { name: 'Veracruz', value: 'VER' },
    { name: 'Yucatán', value: 'YUC' },
    { name: 'Zacatecas', value: 'ZAC' },
    { name: 'Ciudad de México', value: 'CDMX' } // Mexico City
] as const;

export const OPTIONS_STATES = {
    [Countries.US]    : USA_STATES,
    [Countries.CANADA]: PROVINCES_AND_TERRITORIES_CANADA,
    [Countries.MEXICO]: MEXICAN_STATES
};
